version: 2
updates:
  # Backend npm dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    reviewers:
      - "zer0spin"
    labels:
      - "dependencies"
      - "security"
      - "backend"
    commit-message:
      prefix: "chore(deps-backend)"
      include: "scope"
    allow:
      - dependency-type: "all"
    # Security updates get higher priority
    security-updates-only: false
    
  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    reviewers:
      - "zer0spin"
    labels:
      - "dependencies"
      - "security"
      - "frontend"
    commit-message:
      prefix: "chore(deps-frontend)"
      include: "scope"
    allow:
      - dependency-type: "all"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "zer0spin"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps-actions)"
      include: "scope"
